language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install -r requirements.txt ; python setup.py install
script:
    - export PEYOTL_CONFIG_FILE="${PWD}/dev/travis.config" ; export PYTHONPATH="$PYTHONPATH:$PWD" ; python setup.py test


